[project]
name = "adata-query"
version = "0.2.0rc0"
description = "Fetch and format data matrices from AnnData"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anndata",
    "autodevice",
    "torch",
]
